name: horas2
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter

  # Backend y almacenamiento
  shared_preferences: ^2.2.3
  #flutter_quill: 9.3.11
  path_provider: ^2.1.4
  sqflite: ^2.3.3+1
  sqflite_common_ffi: ^2.3.3
  sqflite_common_ffi_web: ^0.4.3+1
    
  youtube_player_iframe: ^4.0.4
  flutter_quill: ^8.6.2
  
  # Para webviews normales
  webview_flutter: ^4.7.0

  # Firebase
  firebase_core: ^2.32.0
  firebase_auth: ^4.20.0
  cloud_firestore: ^4.17.5
  firebase_core_web: ^2.17.5

  # Utiler√≠as
  flutter_dotenv: ^5.2.1
  http: ^1.2.2
  path: ^1.9.0
  lucide_icons: ^0.257.0
  crypto: ^3.0.3
  supabase_flutter: ^2.2.5

  # Frontend
  google_fonts: ^5.1.0
  table_calendar: ^3.0.9
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.10+1
  uuid: ^4.0.0
  file_picker: ^6.2.1
  permission_handler: ^11.3.1
  image_picker: ^1.1.2
  url_launcher: ^6.3.1
  flutter_markdown: ^0.7.4+3
  flutter_tts: ^3.8.5
  syncfusion_flutter_pdf: ^24.2.9
  provider: ^6.1.5+1
  go_router: ^14.6.2
  connectivity_plus: ^6.1.5
  shimmer: ^3.0.0
  audioplayers: ^6.4.0
  just_audio: ^0.9.42
  audio_session: ^0.1.21
  intl: ^0.18.1
  #flutter_quill: ^9.3.11
  #flutter_quill_extensions: ^9.3.4


dependency_overrides:
  flutter_keyboard_visibility: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/iconapp.png"
  min_sdk_android: 21