name: horas2
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter

  # Backend y almacenamiento
  shared_preferences: ^2.2.3
  path_provider: ^2.1.4
  sqflite: ^2.3.3+1
  sqflite_common_ffi: ^2.3.3
  sqflite_common_ffi_web: ^0.4.3+1
    
  youtube_player_iframe: ^5.1.3
  webview_flutter: ^4.7.0

  # Firebase (Versiones compatibles para 2024/2025)
  # Se usa ^ para permitir que el versionador encuentre la mejor compatibilidad
  firebase_core: ^3.10.1
  firebase_auth: ^5.4.1
  cloud_firestore: ^5.6.0

  # Utilerías
  flutter_dotenv: ^6.0.0
  http: ^1.2.2
  path: ^1.9.0
  lucide_icons: ^0.257.0
  crypto: ^3.0.3
  supabase_flutter: ^2.12.0

  # Frontend
  google_fonts: ^6.3.0
  table_calendar: ^3.0.9
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.10+1
  uuid: ^4.0.0
  file_picker: ^8.0.7
  permission_handler: ^11.3.1
  image_picker: ^1.1.2
  url_launcher: ^6.3.1
  flutter_markdown: ^0.7.4+3
  flutter_tts: ^4.2.5
  syncfusion_flutter_pdf: ^20.2.0 # Ajustada para mayor compatibilidad
  provider: ^6.1.5+1
  go_router: ^15.1.2
  connectivity_plus: ^7.0.0
  shimmer: ^3.0.0
  just_audio: ^0.9.42
  audio_session: ^0.1.21
  intl: ^0.19.0
  syncfusion_flutter_charts: ^20.4.54

dependency_overrides:
  # Se mantiene solo lo necesario. 
  # Se eliminó firebase_auth_platform_interface porque ya es nativo en las versiones de arriba.
  flutter_keyboard_visibility: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/iconapp.png"
  min_sdk_android: 21